-- Intentionally empty.
--
-- The original single-user schema used anonymous read/write policies and
-- contained authored-plan examples. Fresh projects begin with the generic,
-- authenticated schema in 20260724000000_multiuser.sql instead.
